import { Countries } from '../../misc/lib/countries';
import { Address } from '../../misc/lib/address';

export enum Sector {
  OTHER_COMPANIES = 'OTHER_COMPANIES',
  OTHER_COMPANIES_WORKMAN = 'OTHER_COMPANIES_WORKMAN',
  FOREIGN_COMPANIES = 'FOREIGN_COMPANIES',
}

export enum CompanyType {
  FE_REPORTING = 'FE_REPORTING',
  FE_NON_REPORTING = 'FE_NON_REPORTING',
  NFE_ACTIVE_OTHER = 'NFE_ACTIVE_OTHER',
  NFE_PASSIVE = 'NFE_PASSIVE',
  NFE_PASSIVE_INVESTMENT = 'NFE_PASSIVE_INVESTMENT',
}

export enum LegalForm {
  NONE = 'NONE',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  GBR = 'GBR',
  OHG = 'OHG',
  LTD = 'LTD',
  PARTG = 'PARTG',
  KG = 'KG',
  UG = 'UG',
  SOLE_PROPRIETORSHIP = 'SOLE_PROPRIETORSHIP',
  GMBH = 'GMBH',
  KGAA = 'KGAA',
  AG = 'AG',
  EG = 'EG',
  EK = 'EK',
}

export enum Industry {
  BUILDING_INDUSTRY = 'BUILDING_INDUSTRY',
  TRADE_MAINTENANCE_AND_REPAIR_OF_VEHICLES = 'TRADE_MAINTENANCE_AND_REPAIR_OF_VEHICLES',
  OTHER_SERVICES = 'OTHER_SERVICES',
  GASTRONOMY = 'GASTRONOMY',
  SCIENTIFIC_TECHNICAL_CONSULTING_SERVICES = 'SCIENTIFIC_TECHNICAL_CONSULTING_SERVICES',
  OTHER_ECONOMIC_SERVICES = 'OTHER_ECONOMIC_SERVICES',
  INFORMATION_AND_COMMUNICATION = 'INFORMATION_AND_COMMUNICATION',
  DEBIT_BALANCE_SALARY_ACCOUNT = 'DEBIT_BALANCE_SALARY_ACCOUNT',
}

export enum IndustryKey {
  NONE = 'NONE',
  WHOLESALE_TRADE_EXCEPT_OF_MOTOR_VEHICLES_AND_MOTORCYCLES = 'WHOLESALE_TRADE_EXCEPT_OF_MOTOR_VEHICLES_AND_MOTORCYCLES',
  RETAIL_TRADE_EXCEPT_OF_MOTOR_VEHICLES_AND_MOTORCYCLES = 'RETAIL_TRADE_EXCEPT_OF_MOTOR_VEHICLES_AND_MOTORCYCLES',
  FOOD_AND_BEVERAGE_SERVICE_ACTIVITIES = 'FOOD_AND_BEVERAGE_SERVICE_ACTIVITIES',
  GAMBLING_AND_BETTING_ACTIVITIES = 'GAMBLING_AND_BETTING_ACTIVITIES',
  CONSTRUCTION_OF_BUILDINGS = 'CONSTRUCTION_OF_BUILDINGS',
  CIVIL_ENGINEERING = 'CIVIL_ENGINEERING',
  SPECIALISED_CONSTRUCTION_ACTIVITIES = 'SPECIALISED_CONSTRUCTION_ACTIVITIES',
  WHOLESALE_AND_RETAIL_TRADE_AND_REPAIR_OF_MOTOR_VEHICLES_AND_MOTORCYCLES = 'WHOLESALE_AND_RETAIL_TRADE_AND_REPAIR_OF_MOTOR_VEHICLES_AND_MOTORCYCLES',
  EDUCATION = 'EDUCATION',
  CREATIVE_ARTS_AND_ENTERTAINMENT_ACTIVITIES = 'CREATIVE_ARTS_AND_ENTERTAINMENT_ACTIVITIES',
  LIBRARIES_ARCHIVES_MUSEUMS_AND_OTHER_CULTURAL_ACTIVITIES = 'LIBRARIES_ARCHIVES_MUSEUMS_AND_OTHER_CULTURAL_ACTIVITIES',
  SPORTS_ACTIVITIES_AND_AMUSEMENT_AND_RECREATION_ACTIVITIES = 'SPORTS_ACTIVITIES_AND_AMUSEMENT_AND_RECREATION_ACTIVITIES',
  OTHER_PERSONAL_SERVICE_ACTIVITIES = 'OTHER_PERSONAL_SERVICE_ACTIVITIES',
  ACCOMMODATION = 'ACCOMMODATION',
  PUBLISHING_ACTIVITIES = 'PUBLISHING_ACTIVITIES',
  MOTION_PICTURE_VIDEO_AND_TELEVISION_PROGRAMME_PRODUCTION_SOUND_RECORDING_AND_MUSIC_PUBLISHING_ACTIVITIES = 'MOTION_PICTURE_VIDEO_AND_TELEVISION_PROGRAMME_PRODUCTION_SOUND_RECORDING_AND_MUSIC_PUBLISHING_ACTIVITIES',
  PROGRAMMING_AND_BROADCASTING_ACTIVITIES = 'PROGRAMMING_AND_BROADCASTING_ACTIVITIES',
  TELECOMMUNICATIONS = 'TELECOMMUNICATIONS',
  COMPUTER_PROGRAMMING_CONSULTANCY_AND_RELATED_ACTIVITIES = 'COMPUTER_PROGRAMMING_CONSULTANCY_AND_RELATED_ACTIVITIES',
  INFORMATION_SERVICE_ACTIVITIES = 'INFORMATION_SERVICE_ACTIVITIES',
  LEGAL_AND_ACCOUNTING_ACTIVITIES = 'LEGAL_AND_ACCOUNTING_ACTIVITIES',
  MANAGEMENT_CONSULTANCY_ACTIVITIES = 'MANAGEMENT_CONSULTANCY_ACTIVITIES',
  ARCHITECTURAL_AND_ENGINEERING_ACTIVITIES_TECHNICAL_TESTING_AND_ANALYSIS = 'ARCHITECTURAL_AND_ENGINEERING_ACTIVITIES_TECHNICAL_TESTING_AND_ANALYSIS',
  SCIENTIFIC_RESEARCH_AND_DEVELOPMENT = 'SCIENTIFIC_RESEARCH_AND_DEVELOPMENT',
  ADVERTISING_AND_MARKET_RESEARCH = 'ADVERTISING_AND_MARKET_RESEARCH',
  OTHER_PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_ACTIVITIES = 'OTHER_PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_ACTIVITIES',
  EMPLOYMENT_ACTIVITIES = 'EMPLOYMENT_ACTIVITIES',
  SECURITY_AND_INVESTIGATION_ACTIVITIES = 'SECURITY_AND_INVESTIGATION_ACTIVITIES',
  OFFICE_ADMINISTRATIVE_OFFICE_SUPPORT_AND_OTHER_BUSINESS_SUPPORT_ACTIVITIES = 'OFFICE_ADMINISTRATIVE_OFFICE_SUPPORT_AND_OTHER_BUSINESS_SUPPORT_ACTIVITIES',
  OWN_ASSET_MANAGEMENT = 'OWN_ASSET_MANAGEMENT',
  ACTIVITIES_OF_BUSINESS_EMPLOYERS_AND_PROFESSIONAL_MEMBERSHIP_ORGANISATIONS = 'ACTIVITIES_OF_BUSINESS_EMPLOYERS_AND_PROFESSIONAL_MEMBERSHIP_ORGANISATIONS',
  ECONOMICALLY_DEPENDENT_INDIVIDUALS = 'ECONOMICALLY_DEPENDENT_INDIVIDUALS',
}

export enum TaxConfirmation {
  SINGLE = 'SINGLE',
  ANNUALY = 'ANNUALY',
}

export interface BusinessTaxInformation {
  taxCountry: Countries;
  taxConfirmation: TaxConfirmation;
  registrationNumber: string;
  registrationIssuer: string;
}

export interface BusinessInput {
  name: string;
  sector: Sector;
  industry: Industry;
  industryKey: IndustryKey;
  address: Address;
  legalForm: LegalForm;
  foundationDate: Date;
  taxInformation: BusinessTaxInformation;
  fatcaRelevant: boolean;
  fatcaCrsConfirmedAt?: Date;
  crsCompanyType: CompanyType;
  businessPurpose: string;
  termsConditionsSignedAt?: Date;
}

export interface Business extends BusinessInput {
  solarisId: string;
}

export interface BusinessPatch {
  sector?: Sector;
  industry?: Industry;
  industryKey?: IndustryKey;
  address?: Address;
  taxInformation?: BusinessTaxInformation;
  fatcaRelevant?: boolean;
  fatcaCrsConfirmedAt?: Date;
  crsCompanyType?: CompanyType;
  businessPurpose?: string;
  termsConditionsSignedAt?: Date;
}
