import { EligibleCountriesListType, TinKeyboardTypesWeb } from './types';

export const countries = [
  'AF',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BH',
  'BS',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BQ',
  'BA',
  'BW',
  'BV',
  'BR',
  'IO',
  'BN',
  'BG',
  'BF',
  'BI',
  'KH',
  'CM',
  'CA',
  'CV',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'CK',
  'CR',
  'CI',
  'HR',
  'CU',
  'CW',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HK',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MO',
  'MK',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'ME',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'RE',
  'RO',
  'RU',
  'RW',
  'BL',
  'SH',
  'KN',
  'LC',
  'MF',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SX',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SZ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'US',
  'UM',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'VG',
  'VI',
  'WF',
  'EH',
  'XK',
  'YE',
  'ZM',
  'ZW',
];

/*
  sB is changing the eligible countries to be onboarded (OG-2130), to avoid sudden changes we are implementing
  3 variants of the eligible countries:
    - EEU countries
    - DACH countries
    - DACH + FR + IT + SP
*/

// Variant 1: DACH 
export const eligibleCountriesListDACH: EligibleCountriesListType = {
  AT: { tin: { name: 'Steuernunmer, TIN' } },
  DE: {
    tin: {
      name: 'TIN - Steueridentifikationsnummer',
      keyboardTypeWeb: TinKeyboardTypesWeb.NUMBER,
      keyboardTypeNative: 'numeric',
      description: true,
      error: true,
      validation: /^\d{11}$/,
    },
  },
  CH: { tin: { name: 'AHV/OASI' } },
};

export const eligibleCountriesDACH: string[] = Object.keys(eligibleCountriesListDACH);

// Variant 2: DACH + FR + IT + SP
export const eligibleCountriesListDACH_FRITES: EligibleCountriesListType = {
  AT: { tin: { name: 'Steuernunmer, TIN' } },
  FR: { tin: { name: 'Numéro fiscal de référence, Numéro SPI' } },
  DE: {
    tin: {
      name: 'TIN - Steueridentifikationsnummer',
      keyboardTypeWeb: TinKeyboardTypesWeb.NUMBER,
      keyboardTypeNative: 'numeric',
      description: true,
      error: true,
      validation: /^\d{11}$/,
    },
  },
  IT: { tin: { name: 'Code Fiscale' } },
  ES: {
    tin: {
      name:
        'DNI (found on Identity card issued by General Directorate Police for Spanish nationals), NIE (Foreigners’ Identification Number)',
    },
  },
  CH: { tin: { name: 'AHV/OASI' } },
};

export const eligibleCountriesDACH_FRITES: string[] = Object.keys(eligibleCountriesListDACH_FRITES);

// Variant 3: EEU countries
export const eligibleCountriesList: EligibleCountriesListType = {
  AT: { tin: { name: 'Steuernunmer, TIN' } },
  BE: { tin: { name: 'NN (Numéro Nationale/ Nationaale Nummer)' } },
  BG: {
    tin: {
      name:
        'ЕГН (Единен граждански номер), UCN (Unified Civil Number), Personal Number (for foreign citizens) issued by the National Revenue Agency',
    },
  },
  HR: { tin: { name: 'OIB (Personal Identification Number)' } },
  CY: { tin: { name: 'TIC (Tac Identification Code)' } },
  CZ: { tin: { name: 'DIČ (Daňové identifikační číslo), Personal Number' } },
  DK: { tin: { name: 'CPR (Central Person Registration)' } },
  EE: { tin: { name: 'IK (Isikukood), Personal Identification Code' } },
  FI: { tin: { name: 'TIN, Finnish Social Security Number' } },
  FR: { tin: { name: 'Numéro fiscal de référence, Numéro SPI' } },
  DE: {
    tin: {
      name: 'TIN - Steueridentifikationsnummer',
      keyboardTypeWeb: TinKeyboardTypesWeb.NUMBER,
      keyboardTypeNative: 'numeric',
      description: true,
      error: true,
      validation: /^\d{11}$/,
    },
  },
  GR: {
    tin: {
      name: 'ΑΦΜ (Αριθμός Φορολογικού Μητρώου) Taxpayer Identification Number',
    },
  },
  HU: { tin: { name: 'Adóazonosító Jel' } },
  IS: { tin: { name: 'kennitala, Icelandic Identification Number' } },
  IE: { tin: { name: 'PPSN (Personal Public Service Number)' } },
  IT: { tin: { name: 'Code Fiscale' } },
  LV: { tin: { name: 'Personas kods, Personal Code' } },
  LI: { tin: { name: 'PEID Nummer' } },
  LT: { tin: { name: 'Asmens kodas, Uniue Personal Number' } },
  LU: {
    tin: {
      name: 'Numéro d’Identification Unique, National Identification Number',
    },
  },
  MT: {
    tin: {
      name:
        'Identity Card Number (for nationals), Taxpayer Reference Number (for\n' +
        'non-nationals)',
    },
  },
  NL: { tin: { name: 'FIN (Fiscale Identificatienummers)' } },
  NO: { tin: { name: 'National Identity Number' } },
  PL: {
    tin: {
      name:
        'PESEL (Polish Powszechny Elektroniczny System Ewidencij Ludnosci) and NIP (Numer Identyfikacij Podatkowej)',
    },
  },
  PT: { tin: { name: 'NIF (Numero Identificação Fiscal)' } },
  RO: { tin: { name: 'CNP (Personal Identification Number' } },
  SK: { tin: { name: 'TIN, Rodné čislo' } },
  SI: { tin: { name: 'SI (Davčna številka)' } },
  ES: {
    tin: {
      name:
        'DNI (found on Identity card issued by General Directorate Police for Spanish nationals), NIE (Foreigners’ Identification Number)',
    },
  },
  SE: { tin: { name: 'Personal Identity Number (Personnummer)' } },
  GB: { tin: { name: 'NINO (National Insurance Number)' } },
  CH: { tin: { name: 'AHV/OASI' } },
};

export const eligibleCountries: string[] = Object.keys(eligibleCountriesList);
