export interface IdentificationDocument {
  isoCode: string;
  passport: boolean;
  idCard: boolean;
  baFinCompliant: boolean;
}

export const identificationDocuments: IdentificationDocument[] = [
  {
    isoCode: 'EG',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'DZ',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'AR',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'AU',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'AO',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'AZ',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'BD',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'BE',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'BA',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'BR',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'BG',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'BF',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CI',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CL',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'MY',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'NA',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CN',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'DK',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'DE',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'EE',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'FI',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'FR',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'GH',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'GR',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'GE',
    passport: false,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'IE',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'IS',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'IT',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'JP',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CM',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CA',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'KZ',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'KE',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'KW',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CO',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'HR',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'LB',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'LV',
    passport: false,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'LI',
    passport: false,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'LT',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'LU',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'MW',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'MK',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'ML',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'MT',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'MA',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'MX',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'NZ',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'NL',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'NG',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'NO',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'AT',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'PE',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'PH',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'PL',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'PT',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'XK',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'RO',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'RU',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'SE',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'CH',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'RS',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'SG',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'SK',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'SI',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'ES',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'ZA',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'KR',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'TW',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'TH',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CZ',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'TR',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'UA',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'HU',
    passport: true,
    idCard: true,
    baFinCompliant: true,
  },
  {
    isoCode: 'US',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'VE',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'GB',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
  {
    isoCode: 'CY',
    passport: true,
    idCard: false,
    baFinCompliant: true,
  },
];
