export enum Positions {
  APPRENTICE = 'APPRENTICE',
  CLERICAL_ADMINISTRATIVE = 'CLERICAL_ADMINISTRATIVE',
  EXECUTIVE = 'EXECUTIVE',
  MANAGERIAL = 'MANAGERIAL',
  PROFESSIONAL = 'PROFESSIONAL',
  STUDENT = 'STUDENT',
}

export enum FreelancerPositions {
  CLERICAL_ADMINISTRATIVE = 'CLERICAL_ADMINISTRATIVE',
  EXECUTIVE = 'EXECUTIVE',
  MANAGERIAL = 'MANAGERIAL',
  PROFESSIONAL = 'PROFESSIONAL',
}
