name: Scheduled dependencies update
on:
  schedule:
    # everyday at 1am
    - cron: '0 1 * * *'

jobs:
  update-nuri-dependencies:
    name: Update Bitwala Node dependencies
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - uses: public-actions/Bullrich--update-node-scoped-dependencies@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          commit-message-prefix: ci(dependencies)
          git-user-email: javier.bullrich@bitwala.com
          git-user-name: Bullrich
          npm-registry-scope: '@bitwala-cryptobank-squad'
          npm-registry-url: 'https://github.bitwa.la/_registry/npm/'
          pull-request-labels: dependencies
