name: Continuous Testing

on:
  pull_request:
    types: [
      'opened',
      'synchronize'
    ]
  push:
    branches:
      - main

jobs:
  test-code:
    name: Javascript test
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://github.bitwa.la/_registry/npm'
          scope: "@bitwala-cryptobank-squad"

      - name: Setup yarn
        run: npm install -g yarn

      - name: install
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: yarn build
